# Generated by Django 4.2.11 on 2024-03-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='DOJ',
            field=models.DateField(null=True),
        ),
    ]
